
"""
Shared MRI utilities for the ADNI Alzheimer's classification project.

Generated by Notebook 2. Imported by Notebooks 3 and 4.

Do not edit this file directly. Edit the generating cell in Notebook 2 and
re-run it, so that the module and the notebook documenting it cannot drift
apart.
"""

from pathlib import Path

import numpy as np
import pydicom

from scipy import ndimage
from skimage.transform import resize


# ============================================================
# Default preprocessing parameters
# ============================================================

LOWER_PERCENTILE = 1
UPPER_PERCENTILE = 99

SIGNAL_THRESHOLD = 0.05
BRAIN_CONTENT_THRESHOLD = 0.70

N_SLICES_PER_PARTICIPANT = 20
IMAGE_SIZE = (224, 224)

# ============================================================
# Anatomical plane for 2D slicing
#
# Axis mapping verified from ImageOrientationPatient across 25
# scans spanning both manufacturers and all three matrix sizes
# in this cohort. Every scan gives row=Posterior, col=Inferior,
# normal=Right, so a fixed axis index is safe here:
#
#   axis 0 -> left-right         -> sagittal
#   axis 1 -> superior-inferior  -> axial
#   axis 2 -> anterior-posterior -> coronal
#
# Coronal is used because the hippocampus is the primary
# biomarker in this project, and coronal is the clinical
# standard plane for medial temporal lobe assessment.
# ============================================================

PLANE_AXIS = {"sagittal": 0, "axial": 1, "coronal": 2}
DEFAULT_PLANE = "coronal"


# ============================================================
# Series discovery
# ============================================================

def find_mri_series(participant_folder,
                    prefer=("MPRAGE", "MP-RAGE", "MP RAGE")):
    """Locate candidate DICOM series for a participant, best first."""

    participant_folder = Path(participant_folder)

    if not participant_folder.exists():
        raise FileNotFoundError(f"No folder for {participant_folder.name}")

    candidates = []

    for sequence_folder in sorted(participant_folder.iterdir()):
        if not sequence_folder.is_dir():
            continue
        for acquisition_folder in sorted(sequence_folder.iterdir()):
            if not acquisition_folder.is_dir():
                continue
            for series_folder in sorted(acquisition_folder.iterdir()):
                if not series_folder.is_dir():
                    continue
                dicom_files = list(series_folder.glob("*.dcm"))
                if not dicom_files:
                    continue
                candidates.append({
                    "path": series_folder,
                    "sequence": sequence_folder.name,
                    "acquisition": acquisition_folder.name,
                    "n_files": len(dicom_files),
                    "preferred": any(
                        t.lower() in sequence_folder.name.lower()
                        for t in prefer
                    ),
                })

    if not candidates:
        raise FileNotFoundError(
            f"No DICOM series found for {participant_folder.name}"
        )

    candidates.sort(key=lambda c: (not c["preferred"], -c["n_files"]))
    return candidates


# ============================================================
# Volume reconstruction
# ============================================================

def load_mri_volume(dicom_folder, enforce_single_series=True,
                    spacing_tolerance=0.30):
    """Load a DICOM series and reconstruct the anatomically ordered volume."""

    dicom_folder = Path(dicom_folder)
    dicom_files = list(dicom_folder.glob("*.dcm"))

    if not dicom_files:
        raise ValueError(f"No DICOM files in {dicom_folder}")

    slices = [pydicom.dcmread(f) for f in dicom_files]

    series_uids = {str(s.SeriesInstanceUID) for s in slices}

    if len(series_uids) > 1:
        message = (
            f"{len(series_uids)} SeriesInstanceUIDs in {dicom_folder.name} "
            f"- these are not a single acquisition"
        )
        if enforce_single_series:
            raise ValueError(message)

    orientation = np.array(slices[0].ImageOrientationPatient, dtype=float)
    slice_normal = np.cross(orientation[:3], orientation[3:])

    def slice_position(s):
        position = np.array(s.ImagePositionPatient, dtype=float)
        return float(np.dot(position, slice_normal))

    slices = sorted(slices, key=slice_position)

    positions = np.array([slice_position(s) for s in slices])
    spacings = np.abs(np.diff(positions))
    median_spacing = float(np.median(spacings)) if spacings.size else 0.0

    if spacings.size:
        uniform = bool(np.all(
            np.abs(spacings - median_spacing)
            <= spacing_tolerance * median_spacing
        ))
    else:
        uniform = True

    volume = np.stack([s.pixel_array for s in slices])

    first = slices[0]

    info = {
        "n_slices": len(slices),
        "shape": volume.shape,
        "row_spacing": float(first.PixelSpacing[0]),
        "column_spacing": float(first.PixelSpacing[1]),
        "slice_spacing": median_spacing,
        "spacing_uniform": uniform,
        "manufacturer": str(getattr(first, "Manufacturer", "Unknown")).strip(),
        "field_strength": float(
            getattr(first, "MagneticFieldStrength", np.nan)),
        "series_description": str(
            getattr(first, "SeriesDescription", "")).strip(),
        "n_series_uids": len(series_uids),
    }

    return volume, slices, info   

# ============================================================
# Intensity normalisation
# ============================================================

def normalize_volume(volume, lower=LOWER_PERCENTILE, upper=UPPER_PERCENTILE):
    """Percentile-clipped scaling to the range 0-1. Background stays zero."""

    nonzero = volume[volume > 0]

    if nonzero.size == 0:
        raise ValueError("Volume contains no non-zero voxels.")

    lower_value = np.percentile(nonzero, lower)
    upper_value = np.percentile(nonzero, upper)

    if upper_value <= lower_value:
        raise ValueError("Invalid intensity range for normalisation.")

    background = volume == 0

    normalized = np.clip(volume.astype(np.float32), lower_value, upper_value)
    normalized = (normalized - lower_value) / (upper_value - lower_value)
    normalized[background] = 0.0

    return normalized


def reorient(volume, plane=DEFAULT_PLANE):
    """
    Move the requested anatomical plane to axis 0 so the existing
    slice-selection code, which iterates axis 0, operates on it.

    The axis swap for coronal and axial is required. moveaxis alone
    yields a rotated image: measured left-right symmetry about the
    vertical midline on a mid-coronal slice is 0.26 without the
    swap and 0.65 with it.

    Resulting in-plane orientation:
      sagittal -> rows = superior-inferior, cols = anterior-posterior
      coronal  -> rows = superior-inferior, cols = left-right
      axial    -> rows = anterior-posterior, cols = left-right
    """

    if plane not in PLANE_AXIS:
        raise ValueError(
            f"plane must be one of {sorted(PLANE_AXIS)}, got {plane!r}"
        )

    out = np.moveaxis(volume, PLANE_AXIS[plane], 0)

    if plane in ("coronal", "axial"):
        out = np.swapaxes(out, 1, 2)

    return out

# ============================================================
# Brain extraction
# ============================================================

def extract_brain_mask(volume, threshold=0.10, erosion_iterations=3,
                       dilation_iterations=3):
    """
    Approximate skull stripping using morphological processing.

    Skull and scalp are bright on T1 and connect to brain tissue through
    the dura, so plain thresholding retains them. Eroding breaks those thin
    connections, the largest surviving component is the brain, and dilating
    restores the original extent.

    This is an approximate skull-stripping approach used before 2D slice extraction.
    It is not equivalent to a dedicated tool such as HD-BET or SynthStrip,
    and this limitation should be considered when interpreting the results.
    """

    mask = volume > threshold

    structure = np.ones((3, 3, 3))

    mask = ndimage.binary_erosion(
        mask, structure=structure, iterations=erosion_iterations)

    labelled, n_components = ndimage.label(mask)

    if n_components == 0:
        return np.ones_like(volume, dtype=bool)

    sizes = ndimage.sum(mask, labelled, range(1, n_components + 1))
    mask = labelled == (int(np.argmax(sizes)) + 1)

    mask = ndimage.binary_dilation(
        mask, structure=structure, iterations=dilation_iterations)

    mask = ndimage.binary_fill_holes(mask)

    return mask


def apply_brain_mask(volume, mask):
    """Zero every voxel outside the brain mask."""

    return volume * mask.astype(volume.dtype)


# ============================================================
# Slice selection
# ============================================================

def calculate_brain_content(volume, threshold=SIGNAL_THRESHOLD):
    """Percentage of pixels carrying meaningful signal, per slice."""

    return np.array([
        np.count_nonzero(s > threshold) / s.size * 100.0
        for s in volume
    ], dtype=np.float32)


def select_informative_slices(brain_content,
                              n_slices=N_SLICES_PER_PARTICIPANT,
                              content_fraction=BRAIN_CONTENT_THRESHOLD):
    """
    Choose n_slices evenly spaced across the informative slice range.

    The original pipeline returned every slice above the content threshold,
    producing roughly 86 contiguous, near-identical slices per participant.
    That inflated the apparent dataset size without adding information and
    was the principal cause of overfitting in the deep learning branch.

    Sampling evenly across the same anatomical range preserves coverage
    while removing the redundancy.
    """

    if brain_content.size == 0:
        raise ValueError("Empty brain-content profile.")

    threshold = brain_content.max() * content_fraction
    valid = np.where(brain_content >= threshold)[0]

    if valid.size == 0:
        raise ValueError("No slices exceed the brain-content threshold.")

    first, last = int(valid[0]), int(valid[-1])

    span = last - first + 1

    if n_slices >= span:
        return np.arange(first, last + 1)

    indices = np.linspace(first, last, n_slices)

    return np.unique(np.round(indices).astype(int))


def resize_slices(volume, indices, image_size=IMAGE_SIZE):
    """Resize the selected coronal slices to a common resolution."""

    return np.stack([
        resize(volume[i], image_size,
               preserve_range=True, anti_aliasing=True).astype(np.float32)
        for i in indices
    ])


# ============================================================
# End-to-end pipeline
# ============================================================

def preprocess_participant(participant_folder,
                           n_slices=N_SLICES_PER_PARTICIPANT,
                           skull_strip=True,
                           image_size=IMAGE_SIZE,
                           plane=DEFAULT_PLANE):
    """
    Run the full preprocessing pipeline for one participant.

    Returns (slices_array, metadata_dict).
    """

    series = find_mri_series(participant_folder)[0]

    volume, _, info = load_mri_volume(series["path"])

    normalized = normalize_volume(volume)

    if skull_strip:
        mask = extract_brain_mask(normalized)
        normalized = apply_brain_mask(normalized, mask)
        brain_fraction = float(mask.mean())
    else:
        brain_fraction = float("nan")

    # Reorient before slice profiling, so brain content and slice
    # selection operate on the requested plane.
    normalized = reorient(normalized, plane)

    content = calculate_brain_content(normalized)
    indices = select_informative_slices(content, n_slices=n_slices)
    slices_array = resize_slices(normalized, indices, image_size)

    metadata = {
        **info,
        "sequence": series["sequence"],
        "acquisition": series["acquisition"],
        "plane": plane,
        "reoriented_shape": list(normalized.shape),
        "selected_indices": indices.tolist(),
        "n_selected": int(len(indices)),
        "skull_stripped": bool(skull_strip),
        "brain_fraction": brain_fraction,
    }

    return slices_array, metadata
